### ISSUE TITLE
Can't remove a spindle recipe by CraftTweaker

### ISSUE THREAD

**Issue by Fireztonez** [DaedalusGame/BetterWithAddons#89]
Hello, I try to remove the Hemp Cloth spindle recipe, for add a Rope recipe using Hemp Fibers.

My script I made for that is :
`mods.betterwithaddons.Spindle.remove(<betterwithmods:material:3>);
mods.betterwithaddons.Spindle.add([<betterwithmods:rope>],<betterwithmods:material:3>*9,false);`

On jei, when I look Spindle recipes using Hemp Fibers, this is little strange, I see both recipe, bot the one for the Hemp Cloth is show like using only one Hemp Fiber, but it using 9 for made a Cloth...
![2018-03-31 15_21_52-minecraft 1 12 2](https://user-images.githubusercontent.com/19277301/38166843-a77f07e2-34f8-11e8-9490-18a561fe365e.png)

Minecraft: 1.12.2
Better With Addons : 0.34
Better With Mods : 2.0.32
Forge : 14.23.2.2640
CraftTweaker: 4.1.6

**Comment by DaedalusGame** [comment]
oh that's nice. The mirror-side of the issue. This one shows 1 item but requires 8.

**Comment by Fireztonez** [comment]
Yes that is strange too!!

**Comment by Fireztonez** [comment]
I see you close the issues, so I guess you have to find the problem!

**Comment by DaedalusGame** [comment]
update is delayed by a few hours because i wiped the config and i will only update if everything works correctly.
edit: my config mistakenly migrated into the BWM config, that should be fixed and will be ready soon

**Comment by Fireztonez** [comment]
Problem still not fix, the recipe for the Hemp Cloth is still there, the only thing have change, now is show in JEI like needed 9 Hemp Fiber.

 Can you look to fix the real problem? My big consern is not fact of showing wrong in JEI, but the fact of the delete recipe doesn't delete the recipe!!

![hemp_cloth](https://user-images.githubusercontent.com/19277301/38257323-05d1f39a-372e-11e8-94df-b57a6a1b0ab8.png)

![hemp_cloth-not-remove](https://user-images.githubusercontent.com/19277301/38257324-05e38a92-372e-11e8-95f9-e38530585ad0.png)

**Comment by DaedalusGame** [comment]
a classic, retrieving the recipe to be removed before the recipe even exists

**Comment by Fireztonez** [comment]
Ok, thank's,
I just see the link to the source code, so I see the hotfix!

Thank's

**Comment by Fireztonez** [comment]
Look like the problem is still present.... JEI still show both recipes.
Can you look if I do everithing right in the script on the first post? If ios not an error from me, I think something wrong on the mod again :-/

Fireztonez

**Comment by DaedalusGame** [comment]
`mods.betterwithaddons.Spindle.remove(<betterwithmods:material:3>*9);`

**Comment by Fireztonez** [comment]
:o thank's!
